---
title: '[Aline] Lista 5'
author: "Aline Maria"
date: "2024-09-06"
output: html_document
---

# Teste da Hipótese

Hipótese: Quanto maior o número de partidos, maior a chance de adotar a TZ

```{r setup, include=FALSE}
pacman::p_load("tidyverse", "readxl", "broom")
```

# Lendo os dados
dados <- read_excel("~/Downloads/1º Semestre/3. Método Quantitativo/R/TZ_banco.xlsx")
colnames(dados)

# Rodando a regressão logística
modelo <- glm(adotatz ~ NEPm, data = dados, family = binomial)

# Resumo do modelo
summary(modelo)

# Explique, de forma sucinta, a escolha do teste, suas potencialidades e limitações.

Considerando que a variável adotatz é uma dependente binária, utilizei uma regressão 
logística binomial para identificar se quanto maior o número de partidos,
maior a chance de adotar a Tarifa Zero (TZ). Em diálogo com a variável dependente,
usei a média do número efetivo de partidos (NEPm), como variável independete, para 
testar a hipótese.

Percebi que é possível estimar a probabilidade de um município adotar a TZ com base
no número de partidos. Além disso, a regressão logística binomial proporcionou 
avaliar se há significância na relação estátistica entre as variáveis.

Dentre os desafios encontrados, identificar o quanto a variável preditora (NEPm)
pode ter relação com outras variáveis, culminando na distorção dos resultados.

